language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - ruby-head
script: "rake spec"
branches:
  only:
    - master
env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.4.3"
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: ruby-head
      env: PUPPET_GEM_VERSION="~> 2.7.0"
notifications:
  email: true
gemfile: Gemfile

